#!/bin/sh

NUM=10;
TIMEOUT=1

if [ -n "$1" ]; then
	NUM=$1
fi

echo 'digraph G { testovaci -> graf }'> heap.digraph
dot -Txlib heap.digraph &

#circo -Txlib heap.digraph &
PID=$!
echo 'PID: '$PID
(for x in $(seq 0 $NUM); do sleep $TIMEOUT; echo -n a; done) | ./heap $NUM
echo killing pid: $PID
kill $PID
