#
# Global makefile to build/test all examples.
#
# $Id: Makefile,v 1.4 2006/12/10 14:48:11 qceleda Exp $
#

all:
	$(MAKE) -C 01.01.led
	$(MAKE) -C 01.02.led
	$(MAKE) -C 01.03.pin
	$(MAKE) -C 01.04.pin
	$(MAKE) -C 02.01.shift
	$(MAKE) -C 02.02.shift
#	$(MAKE) -C 02.03.i2c
#	$(MAKE) -C 02.04.i2c
#	$(MAKE) -C 02.05.i2c
	$(MAKE) -C 03.01.rs232
	$(MAKE) -C 03.02.rs232
	$(MAKE) -C 03.03.rs232
	$(MAKE) -C 03.04.rs232
	$(MAKE) -C 03.05.rs232
	$(MAKE) -C 03.06.rs232/avr
	$(MAKE) -C 03.07.rs232
#	$(MAKE) -C 04.01.lcd
#	$(MAKE) -C 04.01.lcd
#	$(MAKE) -C 04.01.lcd
#	$(MAKE) -C 04.01.lcd
	$(MAKE) -C 05.01.flash
	$(MAKE) -C 05.02.eeprom
	$(MAKE) -C 05.03.sram
	$(MAKE) -C 07.01.int.ext
	$(MAKE) -C 07.02.int.led
	$(MAKE) -C 07.03.int.rtc
	$(MAKE) -C 07.04.int.uart
	$(MAKE) -C 07.05.int.uart
	$(MAKE) -C 09.01.wdt
	$(MAKE) -C 09.02.wdt.reset
	$(MAKE) -C 09.03.assert

clean:
	$(MAKE) -C 01.01.led clean
	$(MAKE) -C 01.02.led clean
	$(MAKE) -C 01.03.pin clean
	$(MAKE) -C 01.04.pin clean
	$(MAKE) -C 02.01.shift clean
	$(MAKE) -C 02.02.shift clean
#	$(MAKE) -C 02.03.i2c clean
#	$(MAKE) -C 02.04.i2c clean
#	$(MAKE) -C 02.05.i2c clean
	$(MAKE) -C 03.01.rs232 clean
	$(MAKE) -C 03.02.rs232 clean
	$(MAKE) -C 03.03.rs232 clean
	$(MAKE) -C 03.04.rs232 clean
	$(MAKE) -C 03.05.rs232 clean
	$(MAKE) -C 03.06.rs232/avr clean
	$(MAKE) -C 03.07.rs232 clean
#	$(MAKE) -C 04.01.lcd clean
#	$(MAKE) -C 04.01.lcd clean
#	$(MAKE) -C 04.01.lcd clean
#	$(MAKE) -C 04.01.lcd clean
	$(MAKE) -C 05.01.flash clean
	$(MAKE) -C 05.02.eeprom clean
	$(MAKE) -C 05.03.sram clean
	$(MAKE) -C 07.01.int.ext clean
	$(MAKE) -C 07.02.int.led clean
	$(MAKE) -C 07.03.int.rtc clean
	$(MAKE) -C 07.04.int.uart clean
	$(MAKE) -C 07.05.int.uart clean
	$(MAKE) -C 09.01.wdt clean
	$(MAKE) -C 09.02.wdt.reset clean
	$(MAKE) -C 09.03.assert clean

